# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'macOS-10.14'
  demands: msbuild

steps:
- template: common-dotnet.yml@templates
- template: common-macos.yml@templates

- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: filePath
    filePath: ./devops/PreBuild.ps1
    arguments: ' MazeCreator MazeCreator.nuspec'

- task: TriggerBuild@3
  inputs:
    definitionIsInCurrentTeamProject: true
    buildDefinition: 'MazeCreator.Windows'
    queueBuildForUserThatTriggeredBuild: true
    ignoreSslCertificateErrors: true
    useSameSourceVersion: false
    useSameBranch: true
    waitForQueuedBuildsToFinish: false
    storeInEnvironmentVariable: false
    authenticationMethod: 'Personal Access Token'
    password: '$(myToken)'
    enableBuildInQueueCondition: false
    dependentOnSuccessfulBuildCondition: false
    dependentOnFailedBuildCondition: false
    checkbuildsoncurrentbranch: false
    failTaskIfConditionsAreNotFulfilled: false

- task: MSBuild@1
  displayName: 'Build solution MazeCreator.Mac.sln'
  inputs:
    solution: MazeCreator.Mac.sln
    configuration: Release

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Xamarin.iOS.MazeCreator.dll'
  inputs:
    PathtoPublish: lib/Release/xamarinios/MazeCreator.dll
    ArtifactName: Xamarin.iOS.MazeCreator.dll

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Xamarin.Mac.MazeCreator.dll'
  inputs:
    PathtoPublish: lib/Release/xamarinmac/MazeCreator.dll
    ArtifactName: Xamarin.Mac.MazeCreator.dll

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Xamarin.tvOS.MazeCreator.dll'
  inputs:
    PathtoPublish: lib/Release/xamarintvos/MazeCreator.dll
    ArtifactName: Xamarin.tvOS.MazeCreator.dll

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Xamarin.watchOS.MazeCreator.dll'
  inputs:
    PathtoPublish: lib/Release/xamarinwatchos/MazeCreator.dll
    ArtifactName: Xamarin.watchOS.MazeCreator.dll




- template: send-telegram.yml@templates
